##############################################################################
#
# GitGub CI workflow syntax spec:
#    https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# Coveralls example:
#    https://github.com/marketplace/actions/coveralls-github-action
#
##############################################################################

name: Build

on:
  # Triggered whenever push to the main branch
  push:
    branches: [ "development_phase1" ]

  # Triggered whenever a pull request is created on main
  pull_request:
    branches: [ "development_phase1" ]
    types: [opened]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-20.04
    
    steps:
      # We want to use GitHub CI checkout version 3 for checking out the branch
      - uses: actions/checkout@v3
      
      # Install some system pacakges
      - name: Install packages
        run: pip3 install --user cpp-coveralls
        
      - name: Install Lcov
        run: sudo apt-get install -y -qq lcov

      # Run CMake to setup compilation flags
      - name: Configure Coverage CMake 
        run: cmake -D COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -B ${{github.workspace}}/build 
      
      # Compile and executables
      - name: Build Coverage
        working-directory: ${{github.workspace}}/build
        run: make

      # Run test suite and compute code coverage
      - name: Run Test Coverage
        working-directory: ${{github.workspace}}/build
        run: make code_coverage
      
      # Upload coverage result to Coverage.io 
      - name: Upload result to Coveralls.io
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
#           path-to-lcov: ${{github.workspace}}/build/coverage.info.cleaned
