
##############################################################################
#
# GitGub CI workflow syntax spec:
#    https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# CodeCov github action setup:
#    https://github.com/codecov/codecov-action
#
# CodeCov badge setup:
#    https://docs.codecov.com/docs/status-badges
#
# version 1.1
##############################################################################

name: Build

on:
  # Triggered whenever push to the main branch
  push:
    branches: [ "development_phase2" ]

  # Triggered whenever a pull request is created on main
  pull_request:
    branches: [ "development_phase2" ]
    types: [opened]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    # Create a container of the latest Ubuntu, other values could be
    # ubuntu-latest, ubuntu-22.04, etc.
    runs-on: ubuntu-22.04
    
    steps:
      # We want to use GitHub CI checkout version 3 to check out our branch
      - uses: actions/checkout@v3
      
      - name: Install colcon extensions
        run:
          sudo apt-get install git
          sudo apt update && sudo apt install locales
          sudo locale-gen en_US en_US.UTF-8
          sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          export LANG=en_US.UTF-8
          locale
          sudo apt install software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install curl
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install python3-colcon-common-extensions
          sudo apt install -y lcov

      # Install some system pacakges
      - name: Install ROS 2 Humble packages
        run: |
          sudo apt update
          sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions
          sudo apt install ros-dev-tools
          sudo apt install ros-humble-gazebo*
          sudo apt install ros-humble-turtlebot3*
          sudo rosdep init
          rosdep update
          rosdep install --from-paths autonomous-warehouse-inspection/src -y --ignore-src

          
        # export TURTLEBOT3_MODEL=waffle
        # export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:`ros2 pkg prefix turtlebot3_gazebo/share/turtlebot3_gazebo/models/
        # export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:${{github.workspace}}/src/autonomous-warehouse-inspection/models

      # Build for test coverage
      - name: Configure CMake flags and build exectables
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --cmake-args -DCOVERAGE=1 --packages-select autonomous-warehouse-inspection
          cat log/latest_build/autonomous-warehouse-inspection/stdout_stderr.log
          find build/autonomous-warehouse-inspection/ | grep -E 'gcno' # catch error -- exepct to see .gcno files
      
      # Run unit test and also check c++ code (and others) for style and static coding errors
      - name: Run unit test and check code error
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --packages-select autonomous-warehouse-inspection
          cat log/latest_test/autonomous-warehouse-inspection/stdout_stderr.log
          find build/autonomous-warehouse-inspection/ | grep -E 'gcda' # catch error -- expect to see .gcda files
          
          colcon test --event-handlers console_direct+ --packages-select pub_sub

      # Generate code coverage test report
      - name: Generate test coverage report
        run: |
          source install/setup.bash
          ros2 run autonomous-warehouse-inspection generate_coverage_report.bash
      
      # Upload coverage result to CodeCov
      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ${{github.workspace}}/install/autonomous-warehouse-inspection/lib/autonomous-warehouse-inspection/coverage_cleaned.info
          # flags: unittests # optional
          # directory: ${{github.workspace}}/install/
          # name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)      
